spring:
  application:
    name: to-do-list
  datasource:
    url: jdbc:h2:mem:to-do-list;DATABASE_TO_LOWER=TRUE
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2
      enabled: true
  security:
    user:
      password: password
      name: billgates@taskapp.com
#      password: password
#      name: elonmusk@taskapp.com